name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install googletrans==4.0.0-rc1

      - name: Translate Markdown File
        run: |
          python translate.py

      # Commit and push the translated files
      - name: Commit translated files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add *.md
          git commit -m "Add translated markdown files" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/tomazstranscak/autoprevod.git HEAD:main
